### ISSUE TITLE
代码数据文件路径

### ISSUE THREAD

**Issue by lixiaoxin215** [MantangGuo/DRLF#1]
parser.add_argument("--dataPath", type=str, default='/home/guo_19/data/train_noiseLevel_10-20-50_4-11.mat', help="Path for loading training data ")请问一下这个路径在哪里，我找了好久没找到

**Comment by MantangGuo** [comment]
这是我本地路径，要替换成你自己训练数据的路径。具体的数据格式请参照dataloader。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: lixiaoxin215 ***@***.***>
发送时间: Saturday, March 16, 2024 8:45:21 PM
收件人: MantangGuo/DRLF ***@***.***>
抄送: Subscribed ***@***.***>
主题: [MantangGuo/DRLF] 代码数据文件路径 (Issue #1)


parser.add_argument("--dataPath", type=str, default='/home/guo_19/data/train_noiseLevel_10-20-50_4-11.mat', help="Path for loading training data ")请问一下这个路径在哪里，我找了好久没找到

―
